# Generated by Django 4.0.6 on 2022-07-23 10:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date',
            field=models.DateField(null=True, verbose_name='startYear'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None, verbose_name='genres'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(max_length=255, null=True, verbose_name='tconst'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='is_adult',
            field=models.BooleanField(verbose_name='isAdult'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=255, verbose_name='primaryTitle'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title_type',
            field=models.CharField(choices=[('short', 'Short'), ('movie', 'Movie')], max_length=255, verbose_name='titleType'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='birthYear'),
        ),
        migrations.AlterField(
            model_name='person',
            name='death_date',
            field=models.DateField(null=True, verbose_name='deathYear'),
        ),
        migrations.AlterField(
            model_name='person',
            name='imdb_id',
            field=models.CharField(max_length=255, null=True, verbose_name='nconst'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=255, verbose_name='primaryName'),
        ),
        migrations.AlterField(
            model_name='personmovie',
            name='category',
            field=models.CharField(max_length=255, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='personmovie',
            name='characters',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, size=None, verbose_name='characters'),
        ),
        migrations.AlterField(
            model_name='personmovie',
            name='job',
            field=models.CharField(max_length=255, verbose_name='job'),
        ),
        migrations.AlterField(
            model_name='personmovie',
            name='order',
            field=models.IntegerField(verbose_name='ordering'),
        ),
    ]
