# Generated by Django 4.0.6 on 2022-07-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_person_movies_alter_movie_genres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='imdb_id',
            field=models.CharField(max_length=255, null=True, verbose_name='nconst'),
        ),
    ]
