# Generated by Django 4.0.6 on 2022-07-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_person_imdb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmovie',
            name='job',
            field=models.CharField(max_length=255, null=True, verbose_name='job'),
        ),
    ]
